spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

infrastructure:
  services:
    aws:
      params:
        mq:
          - username: rabbitmq
            password: rabbitmq
            hostname: localhost
        database:
          - username: postgres
            password: root
            hostname: jdbc:postgresql://localhost:5432/postgres